// flow-typed signature: 340dfc7dd723b9795213e5c9536d718f
// flow-typed version: <<STUB>>/nuka-carousel_v4.2.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nuka-carousel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nuka-carousel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nuka-carousel/es/default-controls' {
  declare module.exports: any;
}

declare module 'nuka-carousel/es/index' {
  declare module.exports: any;
}

declare module 'nuka-carousel/lib/default-controls' {
  declare module.exports: any;
}

declare module 'nuka-carousel/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nuka-carousel/es/default-controls.js' {
  declare module.exports: $Exports<'nuka-carousel/es/default-controls'>;
}
declare module 'nuka-carousel/es/index.js' {
  declare module.exports: $Exports<'nuka-carousel/es/index'>;
}
declare module 'nuka-carousel/index' {
  declare module.exports: $Exports<'nuka-carousel'>;
}
declare module 'nuka-carousel/index.js' {
  declare module.exports: $Exports<'nuka-carousel'>;
}
declare module 'nuka-carousel/lib/default-controls.js' {
  declare module.exports: $Exports<'nuka-carousel/lib/default-controls'>;
}
declare module 'nuka-carousel/lib/index.js' {
  declare module.exports: $Exports<'nuka-carousel/lib/index'>;
}
