// flow-typed signature: 09f03d071984a2915378d39f0da64d67
// flow-typed version: <<STUB>>/react-static_v5.1.8/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-static'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-static' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-static/examples/animated-routes/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/animated-routes/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/animated-routes/src/containers/About' {
  declare module.exports: any;
}

declare module 'react-static/examples/animated-routes/src/containers/Blog' {
  declare module.exports: any;
}

declare module 'react-static/examples/animated-routes/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/animated-routes/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/animated-routes/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/animated-routes/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo-redux/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo-redux/src/connectors/apollo' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo-redux/src/connectors/redux/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo-redux/src/connectors/redux/reducers/counter' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo-redux/src/connectors/redux/reducers/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo-redux/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo-redux/src/containers/About' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo-redux/src/containers/Blog' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo-redux/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo-redux/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo-redux/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo-redux/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo/src/connectors/apollo' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo/src/containers/About' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo/src/containers/Blog' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/apollo/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic-prismic/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic-prismic/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic-prismic/src/containers/About' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic-prismic/src/containers/Blog' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic-prismic/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic-prismic/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic-prismic/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic-prismic/src/prismic/config' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic-prismic/src/prismic/fetch' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic-prismic/src/prismic/transformer' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic-prismic/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic/src/containers/About' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic/src/containers/Blog' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/basic/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/blank/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/blank/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/blank/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/cordova/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/cordova/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/cordova/src/containers/Geolocation' {
  declare module.exports: any;
}

declare module 'react-static/examples/cordova/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/cordova/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/cordova/src/utils/Device' {
  declare module.exports: any;
}

declare module 'react-static/examples/cordova/src/utils/Geolocation' {
  declare module.exports: any;
}

declare module 'react-static/examples/cordova/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/custom-routing/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/custom-routing/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/custom-routing/src/containers/About' {
  declare module.exports: any;
}

declare module 'react-static/examples/custom-routing/src/containers/Blog' {
  declare module.exports: any;
}

declare module 'react-static/examples/custom-routing/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/custom-routing/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/custom-routing/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/custom-routing/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/dynamic-imports/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/dynamic-imports/src/components/MyComponent' {
  declare module.exports: any;
}

declare module 'react-static/examples/dynamic-imports/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/dynamic-imports/src/containers/About' {
  declare module.exports: any;
}

declare module 'react-static/examples/dynamic-imports/src/containers/Blog' {
  declare module.exports: any;
}

declare module 'react-static/examples/dynamic-imports/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/dynamic-imports/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/dynamic-imports/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/dynamic-imports/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/components/ForgotPasswordForm' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/components/Navigation' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/components/PasswordChangeForm' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/components/SignInForm' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/components/SignOutForm' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/components/SignUpForm' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/containers/About' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/containers/Account' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/containers/Blog' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/containers/Dashboard' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/containers/ForgotPassword' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/containers/SignIn' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/containers/SignOut' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/containers/SignUp' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/firebase/auth' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/firebase/db' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/firebase/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/session/withAuthentication' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/src/session/withAuthorization' {
  declare module.exports: any;
}

declare module 'react-static/examples/firebase-auth/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous-tailwind/postcss.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous-tailwind/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous-tailwind/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous-tailwind/src/containers/About' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous-tailwind/src/containers/Blog' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous-tailwind/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous-tailwind/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous-tailwind/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous-tailwind/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous-tailwind/tailwind' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous/src/containers/About' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous/src/containers/Blog' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/glamorous/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/graphql-request/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/graphql-request/src/components/Header' {
  declare module.exports: any;
}

declare module 'react-static/examples/graphql-request/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/graphql-request/src/pages/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/graphql-request/src/pages/About' {
  declare module.exports: any;
}

declare module 'react-static/examples/graphql-request/src/pages/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/graphql-request/src/pages/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/graphql-request/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/less-antdesign/src/containers/Blog' {
  declare module.exports: any;
}

declare module 'react-static/examples/less-antdesign/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/less-antdesign/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/less-antdesign/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/less-antdesign/src/path-alias-example/component' {
  declare module.exports: any;
}

declare module 'react-static/examples/less-antdesign/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/less-antdesign/webpack.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/material-ui/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/material-ui/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/material-ui/src/containers/About' {
  declare module.exports: any;
}

declare module 'react-static/examples/material-ui/src/containers/Blog' {
  declare module.exports: any;
}

declare module 'react-static/examples/material-ui/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/material-ui/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/material-ui/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/material-ui/src/theme' {
  declare module.exports: any;
}

declare module 'react-static/examples/material-ui/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/non-static-routing/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/non-static-routing/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/non-static-routing/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/non-static-routing/src/containers/NonStatic' {
  declare module.exports: any;
}

declare module 'react-static/examples/non-static-routing/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/non-static-routing/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/preact/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/preact/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/preact/src/containers/About' {
  declare module.exports: any;
}

declare module 'react-static/examples/preact/src/containers/Blog' {
  declare module.exports: any;
}

declare module 'react-static/examples/preact/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/preact/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/preact/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/preact/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/redux/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/redux/src/connectors/redux/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/redux/src/connectors/redux/reducers/counter' {
  declare module.exports: any;
}

declare module 'react-static/examples/redux/src/connectors/redux/reducers/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/redux/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/redux/src/containers/About' {
  declare module.exports: any;
}

declare module 'react-static/examples/redux/src/containers/Blog' {
  declare module.exports: any;
}

declare module 'react-static/examples/redux/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/redux/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/redux/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/redux/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/sass/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/sass/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/sass/src/containers/About' {
  declare module.exports: any;
}

declare module 'react-static/examples/sass/src/containers/Blog' {
  declare module.exports: any;
}

declare module 'react-static/examples/sass/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/sass/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/sass/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/sass/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/styled-components/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/styled-components/src/containers/404' {
  declare module.exports: any;
}

declare module 'react-static/examples/styled-components/src/containers/About' {
  declare module.exports: any;
}

declare module 'react-static/examples/styled-components/src/containers/Blog' {
  declare module.exports: any;
}

declare module 'react-static/examples/styled-components/src/containers/Home' {
  declare module.exports: any;
}

declare module 'react-static/examples/styled-components/src/containers/Post' {
  declare module.exports: any;
}

declare module 'react-static/examples/styled-components/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/styled-components/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/tailwindcss/src/App' {
  declare module.exports: any;
}

declare module 'react-static/examples/tailwindcss/src/index' {
  declare module.exports: any;
}

declare module 'react-static/examples/tailwindcss/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/tailwindcss/tailwind.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/typescript/static.config' {
  declare module.exports: any;
}

declare module 'react-static/examples/typescript/webpack.config' {
  declare module.exports: any;
}

declare module 'react-static/lib/commands/build' {
  declare module.exports: any;
}

declare module 'react-static/lib/commands/create' {
  declare module.exports: any;
}

declare module 'react-static/lib/commands/index' {
  declare module.exports: any;
}

declare module 'react-static/lib/commands/start' {
  declare module.exports: any;
}

declare module 'react-static/lib/index' {
  declare module.exports: any;
}

declare module 'react-static/lib/RootComponents' {
  declare module.exports: any;
}

declare module 'react-static/lib/shared' {
  declare module.exports: any;
}

declare module 'react-static/lib/static' {
  declare module.exports: any;
}

declare module 'react-static/lib/utils' {
  declare module.exports: any;
}

declare module 'react-static/lib/utils/ScrollTo' {
  declare module.exports: any;
}

declare module 'react-static/lib/webpack/index' {
  declare module.exports: any;
}

declare module 'react-static/lib/webpack/rules/cssLoader' {
  declare module.exports: any;
}

declare module 'react-static/lib/webpack/rules/fileLoader' {
  declare module.exports: any;
}

declare module 'react-static/lib/webpack/rules/index' {
  declare module.exports: any;
}

declare module 'react-static/lib/webpack/rules/jsLoader' {
  declare module.exports: any;
}

declare module 'react-static/lib/webpack/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'react-static/lib/webpack/webpack.config.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-static/examples/animated-routes/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/animated-routes/src/App'>;
}
declare module 'react-static/examples/animated-routes/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/animated-routes/src/containers/404'>;
}
declare module 'react-static/examples/animated-routes/src/containers/About.js' {
  declare module.exports: $Exports<'react-static/examples/animated-routes/src/containers/About'>;
}
declare module 'react-static/examples/animated-routes/src/containers/Blog.js' {
  declare module.exports: $Exports<'react-static/examples/animated-routes/src/containers/Blog'>;
}
declare module 'react-static/examples/animated-routes/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/animated-routes/src/containers/Home'>;
}
declare module 'react-static/examples/animated-routes/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/examples/animated-routes/src/containers/Post'>;
}
declare module 'react-static/examples/animated-routes/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/animated-routes/src/index'>;
}
declare module 'react-static/examples/animated-routes/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/animated-routes/static.config'>;
}
declare module 'react-static/examples/apollo-redux/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/apollo-redux/src/App'>;
}
declare module 'react-static/examples/apollo-redux/src/connectors/apollo.js' {
  declare module.exports: $Exports<'react-static/examples/apollo-redux/src/connectors/apollo'>;
}
declare module 'react-static/examples/apollo-redux/src/connectors/redux/index.js' {
  declare module.exports: $Exports<'react-static/examples/apollo-redux/src/connectors/redux/index'>;
}
declare module 'react-static/examples/apollo-redux/src/connectors/redux/reducers/counter.js' {
  declare module.exports: $Exports<'react-static/examples/apollo-redux/src/connectors/redux/reducers/counter'>;
}
declare module 'react-static/examples/apollo-redux/src/connectors/redux/reducers/index.js' {
  declare module.exports: $Exports<'react-static/examples/apollo-redux/src/connectors/redux/reducers/index'>;
}
declare module 'react-static/examples/apollo-redux/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/apollo-redux/src/containers/404'>;
}
declare module 'react-static/examples/apollo-redux/src/containers/About.js' {
  declare module.exports: $Exports<'react-static/examples/apollo-redux/src/containers/About'>;
}
declare module 'react-static/examples/apollo-redux/src/containers/Blog.js' {
  declare module.exports: $Exports<'react-static/examples/apollo-redux/src/containers/Blog'>;
}
declare module 'react-static/examples/apollo-redux/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/apollo-redux/src/containers/Home'>;
}
declare module 'react-static/examples/apollo-redux/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/examples/apollo-redux/src/containers/Post'>;
}
declare module 'react-static/examples/apollo-redux/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/apollo-redux/src/index'>;
}
declare module 'react-static/examples/apollo-redux/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/apollo-redux/static.config'>;
}
declare module 'react-static/examples/apollo/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/apollo/src/App'>;
}
declare module 'react-static/examples/apollo/src/connectors/apollo.js' {
  declare module.exports: $Exports<'react-static/examples/apollo/src/connectors/apollo'>;
}
declare module 'react-static/examples/apollo/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/apollo/src/containers/404'>;
}
declare module 'react-static/examples/apollo/src/containers/About.js' {
  declare module.exports: $Exports<'react-static/examples/apollo/src/containers/About'>;
}
declare module 'react-static/examples/apollo/src/containers/Blog.js' {
  declare module.exports: $Exports<'react-static/examples/apollo/src/containers/Blog'>;
}
declare module 'react-static/examples/apollo/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/apollo/src/containers/Home'>;
}
declare module 'react-static/examples/apollo/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/examples/apollo/src/containers/Post'>;
}
declare module 'react-static/examples/apollo/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/apollo/src/index'>;
}
declare module 'react-static/examples/apollo/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/apollo/static.config'>;
}
declare module 'react-static/examples/basic-prismic/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/basic-prismic/src/App'>;
}
declare module 'react-static/examples/basic-prismic/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/basic-prismic/src/containers/404'>;
}
declare module 'react-static/examples/basic-prismic/src/containers/About.js' {
  declare module.exports: $Exports<'react-static/examples/basic-prismic/src/containers/About'>;
}
declare module 'react-static/examples/basic-prismic/src/containers/Blog.js' {
  declare module.exports: $Exports<'react-static/examples/basic-prismic/src/containers/Blog'>;
}
declare module 'react-static/examples/basic-prismic/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/basic-prismic/src/containers/Home'>;
}
declare module 'react-static/examples/basic-prismic/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/examples/basic-prismic/src/containers/Post'>;
}
declare module 'react-static/examples/basic-prismic/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/basic-prismic/src/index'>;
}
declare module 'react-static/examples/basic-prismic/src/prismic/config.js' {
  declare module.exports: $Exports<'react-static/examples/basic-prismic/src/prismic/config'>;
}
declare module 'react-static/examples/basic-prismic/src/prismic/fetch.js' {
  declare module.exports: $Exports<'react-static/examples/basic-prismic/src/prismic/fetch'>;
}
declare module 'react-static/examples/basic-prismic/src/prismic/transformer.js' {
  declare module.exports: $Exports<'react-static/examples/basic-prismic/src/prismic/transformer'>;
}
declare module 'react-static/examples/basic-prismic/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/basic-prismic/static.config'>;
}
declare module 'react-static/examples/basic/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/basic/src/App'>;
}
declare module 'react-static/examples/basic/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/basic/src/containers/404'>;
}
declare module 'react-static/examples/basic/src/containers/About.js' {
  declare module.exports: $Exports<'react-static/examples/basic/src/containers/About'>;
}
declare module 'react-static/examples/basic/src/containers/Blog.js' {
  declare module.exports: $Exports<'react-static/examples/basic/src/containers/Blog'>;
}
declare module 'react-static/examples/basic/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/basic/src/containers/Home'>;
}
declare module 'react-static/examples/basic/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/examples/basic/src/containers/Post'>;
}
declare module 'react-static/examples/basic/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/basic/src/index'>;
}
declare module 'react-static/examples/basic/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/basic/static.config'>;
}
declare module 'react-static/examples/blank/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/blank/src/App'>;
}
declare module 'react-static/examples/blank/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/blank/src/index'>;
}
declare module 'react-static/examples/blank/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/blank/static.config'>;
}
declare module 'react-static/examples/cordova/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/cordova/src/App'>;
}
declare module 'react-static/examples/cordova/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/cordova/src/containers/404'>;
}
declare module 'react-static/examples/cordova/src/containers/Geolocation.js' {
  declare module.exports: $Exports<'react-static/examples/cordova/src/containers/Geolocation'>;
}
declare module 'react-static/examples/cordova/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/cordova/src/containers/Home'>;
}
declare module 'react-static/examples/cordova/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/cordova/src/index'>;
}
declare module 'react-static/examples/cordova/src/utils/Device.js' {
  declare module.exports: $Exports<'react-static/examples/cordova/src/utils/Device'>;
}
declare module 'react-static/examples/cordova/src/utils/Geolocation.js' {
  declare module.exports: $Exports<'react-static/examples/cordova/src/utils/Geolocation'>;
}
declare module 'react-static/examples/cordova/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/cordova/static.config'>;
}
declare module 'react-static/examples/custom-routing/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/custom-routing/src/App'>;
}
declare module 'react-static/examples/custom-routing/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/custom-routing/src/containers/404'>;
}
declare module 'react-static/examples/custom-routing/src/containers/About.js' {
  declare module.exports: $Exports<'react-static/examples/custom-routing/src/containers/About'>;
}
declare module 'react-static/examples/custom-routing/src/containers/Blog.js' {
  declare module.exports: $Exports<'react-static/examples/custom-routing/src/containers/Blog'>;
}
declare module 'react-static/examples/custom-routing/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/custom-routing/src/containers/Home'>;
}
declare module 'react-static/examples/custom-routing/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/examples/custom-routing/src/containers/Post'>;
}
declare module 'react-static/examples/custom-routing/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/custom-routing/src/index'>;
}
declare module 'react-static/examples/custom-routing/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/custom-routing/static.config'>;
}
declare module 'react-static/examples/dynamic-imports/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/dynamic-imports/src/App'>;
}
declare module 'react-static/examples/dynamic-imports/src/components/MyComponent.js' {
  declare module.exports: $Exports<'react-static/examples/dynamic-imports/src/components/MyComponent'>;
}
declare module 'react-static/examples/dynamic-imports/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/dynamic-imports/src/containers/404'>;
}
declare module 'react-static/examples/dynamic-imports/src/containers/About.js' {
  declare module.exports: $Exports<'react-static/examples/dynamic-imports/src/containers/About'>;
}
declare module 'react-static/examples/dynamic-imports/src/containers/Blog.js' {
  declare module.exports: $Exports<'react-static/examples/dynamic-imports/src/containers/Blog'>;
}
declare module 'react-static/examples/dynamic-imports/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/dynamic-imports/src/containers/Home'>;
}
declare module 'react-static/examples/dynamic-imports/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/examples/dynamic-imports/src/containers/Post'>;
}
declare module 'react-static/examples/dynamic-imports/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/dynamic-imports/src/index'>;
}
declare module 'react-static/examples/dynamic-imports/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/dynamic-imports/static.config'>;
}
declare module 'react-static/examples/firebase-auth/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/App'>;
}
declare module 'react-static/examples/firebase-auth/src/components/ForgotPasswordForm.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/components/ForgotPasswordForm'>;
}
declare module 'react-static/examples/firebase-auth/src/components/Navigation.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/components/Navigation'>;
}
declare module 'react-static/examples/firebase-auth/src/components/PasswordChangeForm.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/components/PasswordChangeForm'>;
}
declare module 'react-static/examples/firebase-auth/src/components/SignInForm.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/components/SignInForm'>;
}
declare module 'react-static/examples/firebase-auth/src/components/SignOutForm.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/components/SignOutForm'>;
}
declare module 'react-static/examples/firebase-auth/src/components/SignUpForm.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/components/SignUpForm'>;
}
declare module 'react-static/examples/firebase-auth/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/containers/404'>;
}
declare module 'react-static/examples/firebase-auth/src/containers/About.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/containers/About'>;
}
declare module 'react-static/examples/firebase-auth/src/containers/Account.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/containers/Account'>;
}
declare module 'react-static/examples/firebase-auth/src/containers/Blog.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/containers/Blog'>;
}
declare module 'react-static/examples/firebase-auth/src/containers/Dashboard.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/containers/Dashboard'>;
}
declare module 'react-static/examples/firebase-auth/src/containers/ForgotPassword.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/containers/ForgotPassword'>;
}
declare module 'react-static/examples/firebase-auth/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/containers/Home'>;
}
declare module 'react-static/examples/firebase-auth/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/containers/Post'>;
}
declare module 'react-static/examples/firebase-auth/src/containers/SignIn.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/containers/SignIn'>;
}
declare module 'react-static/examples/firebase-auth/src/containers/SignOut.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/containers/SignOut'>;
}
declare module 'react-static/examples/firebase-auth/src/containers/SignUp.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/containers/SignUp'>;
}
declare module 'react-static/examples/firebase-auth/src/firebase/auth.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/firebase/auth'>;
}
declare module 'react-static/examples/firebase-auth/src/firebase/db.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/firebase/db'>;
}
declare module 'react-static/examples/firebase-auth/src/firebase/index.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/firebase/index'>;
}
declare module 'react-static/examples/firebase-auth/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/index'>;
}
declare module 'react-static/examples/firebase-auth/src/session/withAuthentication.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/session/withAuthentication'>;
}
declare module 'react-static/examples/firebase-auth/src/session/withAuthorization.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/src/session/withAuthorization'>;
}
declare module 'react-static/examples/firebase-auth/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/firebase-auth/static.config'>;
}
declare module 'react-static/examples/glamorous-tailwind/postcss.config.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous-tailwind/postcss.config'>;
}
declare module 'react-static/examples/glamorous-tailwind/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous-tailwind/src/App'>;
}
declare module 'react-static/examples/glamorous-tailwind/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous-tailwind/src/containers/404'>;
}
declare module 'react-static/examples/glamorous-tailwind/src/containers/About.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous-tailwind/src/containers/About'>;
}
declare module 'react-static/examples/glamorous-tailwind/src/containers/Blog.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous-tailwind/src/containers/Blog'>;
}
declare module 'react-static/examples/glamorous-tailwind/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous-tailwind/src/containers/Home'>;
}
declare module 'react-static/examples/glamorous-tailwind/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous-tailwind/src/containers/Post'>;
}
declare module 'react-static/examples/glamorous-tailwind/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous-tailwind/src/index'>;
}
declare module 'react-static/examples/glamorous-tailwind/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous-tailwind/static.config'>;
}
declare module 'react-static/examples/glamorous-tailwind/tailwind.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous-tailwind/tailwind'>;
}
declare module 'react-static/examples/glamorous/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous/src/App'>;
}
declare module 'react-static/examples/glamorous/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous/src/containers/404'>;
}
declare module 'react-static/examples/glamorous/src/containers/About.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous/src/containers/About'>;
}
declare module 'react-static/examples/glamorous/src/containers/Blog.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous/src/containers/Blog'>;
}
declare module 'react-static/examples/glamorous/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous/src/containers/Home'>;
}
declare module 'react-static/examples/glamorous/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous/src/containers/Post'>;
}
declare module 'react-static/examples/glamorous/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous/src/index'>;
}
declare module 'react-static/examples/glamorous/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/glamorous/static.config'>;
}
declare module 'react-static/examples/graphql-request/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/graphql-request/src/App'>;
}
declare module 'react-static/examples/graphql-request/src/components/Header.js' {
  declare module.exports: $Exports<'react-static/examples/graphql-request/src/components/Header'>;
}
declare module 'react-static/examples/graphql-request/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/graphql-request/src/index'>;
}
declare module 'react-static/examples/graphql-request/src/pages/404.js' {
  declare module.exports: $Exports<'react-static/examples/graphql-request/src/pages/404'>;
}
declare module 'react-static/examples/graphql-request/src/pages/About.js' {
  declare module.exports: $Exports<'react-static/examples/graphql-request/src/pages/About'>;
}
declare module 'react-static/examples/graphql-request/src/pages/Home.js' {
  declare module.exports: $Exports<'react-static/examples/graphql-request/src/pages/Home'>;
}
declare module 'react-static/examples/graphql-request/src/pages/Post.js' {
  declare module.exports: $Exports<'react-static/examples/graphql-request/src/pages/Post'>;
}
declare module 'react-static/examples/graphql-request/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/graphql-request/static.config'>;
}
declare module 'react-static/examples/less-antdesign/src/containers/Blog.js' {
  declare module.exports: $Exports<'react-static/examples/less-antdesign/src/containers/Blog'>;
}
declare module 'react-static/examples/less-antdesign/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/less-antdesign/src/containers/Home'>;
}
declare module 'react-static/examples/less-antdesign/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/examples/less-antdesign/src/containers/Post'>;
}
declare module 'react-static/examples/less-antdesign/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/less-antdesign/src/index'>;
}
declare module 'react-static/examples/less-antdesign/src/path-alias-example/component.js' {
  declare module.exports: $Exports<'react-static/examples/less-antdesign/src/path-alias-example/component'>;
}
declare module 'react-static/examples/less-antdesign/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/less-antdesign/static.config'>;
}
declare module 'react-static/examples/less-antdesign/webpack.config.js' {
  declare module.exports: $Exports<'react-static/examples/less-antdesign/webpack.config'>;
}
declare module 'react-static/examples/material-ui/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/material-ui/src/App'>;
}
declare module 'react-static/examples/material-ui/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/material-ui/src/containers/404'>;
}
declare module 'react-static/examples/material-ui/src/containers/About.js' {
  declare module.exports: $Exports<'react-static/examples/material-ui/src/containers/About'>;
}
declare module 'react-static/examples/material-ui/src/containers/Blog.js' {
  declare module.exports: $Exports<'react-static/examples/material-ui/src/containers/Blog'>;
}
declare module 'react-static/examples/material-ui/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/material-ui/src/containers/Home'>;
}
declare module 'react-static/examples/material-ui/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/examples/material-ui/src/containers/Post'>;
}
declare module 'react-static/examples/material-ui/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/material-ui/src/index'>;
}
declare module 'react-static/examples/material-ui/src/theme.js' {
  declare module.exports: $Exports<'react-static/examples/material-ui/src/theme'>;
}
declare module 'react-static/examples/material-ui/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/material-ui/static.config'>;
}
declare module 'react-static/examples/non-static-routing/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/non-static-routing/src/App'>;
}
declare module 'react-static/examples/non-static-routing/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/non-static-routing/src/containers/404'>;
}
declare module 'react-static/examples/non-static-routing/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/non-static-routing/src/containers/Home'>;
}
declare module 'react-static/examples/non-static-routing/src/containers/NonStatic.js' {
  declare module.exports: $Exports<'react-static/examples/non-static-routing/src/containers/NonStatic'>;
}
declare module 'react-static/examples/non-static-routing/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/non-static-routing/src/index'>;
}
declare module 'react-static/examples/non-static-routing/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/non-static-routing/static.config'>;
}
declare module 'react-static/examples/preact/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/preact/src/App'>;
}
declare module 'react-static/examples/preact/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/preact/src/containers/404'>;
}
declare module 'react-static/examples/preact/src/containers/About.js' {
  declare module.exports: $Exports<'react-static/examples/preact/src/containers/About'>;
}
declare module 'react-static/examples/preact/src/containers/Blog.js' {
  declare module.exports: $Exports<'react-static/examples/preact/src/containers/Blog'>;
}
declare module 'react-static/examples/preact/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/preact/src/containers/Home'>;
}
declare module 'react-static/examples/preact/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/examples/preact/src/containers/Post'>;
}
declare module 'react-static/examples/preact/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/preact/src/index'>;
}
declare module 'react-static/examples/preact/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/preact/static.config'>;
}
declare module 'react-static/examples/redux/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/redux/src/App'>;
}
declare module 'react-static/examples/redux/src/connectors/redux/index.js' {
  declare module.exports: $Exports<'react-static/examples/redux/src/connectors/redux/index'>;
}
declare module 'react-static/examples/redux/src/connectors/redux/reducers/counter.js' {
  declare module.exports: $Exports<'react-static/examples/redux/src/connectors/redux/reducers/counter'>;
}
declare module 'react-static/examples/redux/src/connectors/redux/reducers/index.js' {
  declare module.exports: $Exports<'react-static/examples/redux/src/connectors/redux/reducers/index'>;
}
declare module 'react-static/examples/redux/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/redux/src/containers/404'>;
}
declare module 'react-static/examples/redux/src/containers/About.js' {
  declare module.exports: $Exports<'react-static/examples/redux/src/containers/About'>;
}
declare module 'react-static/examples/redux/src/containers/Blog.js' {
  declare module.exports: $Exports<'react-static/examples/redux/src/containers/Blog'>;
}
declare module 'react-static/examples/redux/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/redux/src/containers/Home'>;
}
declare module 'react-static/examples/redux/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/examples/redux/src/containers/Post'>;
}
declare module 'react-static/examples/redux/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/redux/src/index'>;
}
declare module 'react-static/examples/redux/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/redux/static.config'>;
}
declare module 'react-static/examples/sass/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/sass/src/App'>;
}
declare module 'react-static/examples/sass/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/sass/src/containers/404'>;
}
declare module 'react-static/examples/sass/src/containers/About.js' {
  declare module.exports: $Exports<'react-static/examples/sass/src/containers/About'>;
}
declare module 'react-static/examples/sass/src/containers/Blog.js' {
  declare module.exports: $Exports<'react-static/examples/sass/src/containers/Blog'>;
}
declare module 'react-static/examples/sass/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/sass/src/containers/Home'>;
}
declare module 'react-static/examples/sass/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/examples/sass/src/containers/Post'>;
}
declare module 'react-static/examples/sass/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/sass/src/index'>;
}
declare module 'react-static/examples/sass/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/sass/static.config'>;
}
declare module 'react-static/examples/styled-components/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/styled-components/src/App'>;
}
declare module 'react-static/examples/styled-components/src/containers/404.js' {
  declare module.exports: $Exports<'react-static/examples/styled-components/src/containers/404'>;
}
declare module 'react-static/examples/styled-components/src/containers/About.js' {
  declare module.exports: $Exports<'react-static/examples/styled-components/src/containers/About'>;
}
declare module 'react-static/examples/styled-components/src/containers/Blog.js' {
  declare module.exports: $Exports<'react-static/examples/styled-components/src/containers/Blog'>;
}
declare module 'react-static/examples/styled-components/src/containers/Home.js' {
  declare module.exports: $Exports<'react-static/examples/styled-components/src/containers/Home'>;
}
declare module 'react-static/examples/styled-components/src/containers/Post.js' {
  declare module.exports: $Exports<'react-static/examples/styled-components/src/containers/Post'>;
}
declare module 'react-static/examples/styled-components/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/styled-components/src/index'>;
}
declare module 'react-static/examples/styled-components/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/styled-components/static.config'>;
}
declare module 'react-static/examples/tailwindcss/src/App.js' {
  declare module.exports: $Exports<'react-static/examples/tailwindcss/src/App'>;
}
declare module 'react-static/examples/tailwindcss/src/index.js' {
  declare module.exports: $Exports<'react-static/examples/tailwindcss/src/index'>;
}
declare module 'react-static/examples/tailwindcss/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/tailwindcss/static.config'>;
}
declare module 'react-static/examples/tailwindcss/tailwind.config.js' {
  declare module.exports: $Exports<'react-static/examples/tailwindcss/tailwind.config'>;
}
declare module 'react-static/examples/typescript/static.config.js' {
  declare module.exports: $Exports<'react-static/examples/typescript/static.config'>;
}
declare module 'react-static/examples/typescript/webpack.config.js' {
  declare module.exports: $Exports<'react-static/examples/typescript/webpack.config'>;
}
declare module 'react-static/lib/commands/build.js' {
  declare module.exports: $Exports<'react-static/lib/commands/build'>;
}
declare module 'react-static/lib/commands/create.js' {
  declare module.exports: $Exports<'react-static/lib/commands/create'>;
}
declare module 'react-static/lib/commands/index.js' {
  declare module.exports: $Exports<'react-static/lib/commands/index'>;
}
declare module 'react-static/lib/commands/start.js' {
  declare module.exports: $Exports<'react-static/lib/commands/start'>;
}
declare module 'react-static/lib/index.js' {
  declare module.exports: $Exports<'react-static/lib/index'>;
}
declare module 'react-static/lib/RootComponents.js' {
  declare module.exports: $Exports<'react-static/lib/RootComponents'>;
}
declare module 'react-static/lib/shared.js' {
  declare module.exports: $Exports<'react-static/lib/shared'>;
}
declare module 'react-static/lib/static.js' {
  declare module.exports: $Exports<'react-static/lib/static'>;
}
declare module 'react-static/lib/utils.js' {
  declare module.exports: $Exports<'react-static/lib/utils'>;
}
declare module 'react-static/lib/utils/ScrollTo.js' {
  declare module.exports: $Exports<'react-static/lib/utils/ScrollTo'>;
}
declare module 'react-static/lib/webpack/index.js' {
  declare module.exports: $Exports<'react-static/lib/webpack/index'>;
}
declare module 'react-static/lib/webpack/rules/cssLoader.js' {
  declare module.exports: $Exports<'react-static/lib/webpack/rules/cssLoader'>;
}
declare module 'react-static/lib/webpack/rules/fileLoader.js' {
  declare module.exports: $Exports<'react-static/lib/webpack/rules/fileLoader'>;
}
declare module 'react-static/lib/webpack/rules/index.js' {
  declare module.exports: $Exports<'react-static/lib/webpack/rules/index'>;
}
declare module 'react-static/lib/webpack/rules/jsLoader.js' {
  declare module.exports: $Exports<'react-static/lib/webpack/rules/jsLoader'>;
}
declare module 'react-static/lib/webpack/webpack.config.dev.js' {
  declare module.exports: $Exports<'react-static/lib/webpack/webpack.config.dev'>;
}
declare module 'react-static/lib/webpack/webpack.config.prod.js' {
  declare module.exports: $Exports<'react-static/lib/webpack/webpack.config.prod'>;
}
